name: CI React

on:
  workflow_dispatch:

jobs:
  build-analize:
    name: Preparar NodeJs y Analizar código
    runs-on: macos-26
    
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Unit tests
        id: tests
        continue-on-error: true
        run: npm test